#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Run one complete outer-fold trial for the RA / RA-ILD TRB project.

Default task:
    outer_repeat = 1
    outer_fold   = 1

Models:
    M0_clinical:
        age + sex
    M1_static_tcr:
        age + sex + static step-02 TCR features
    M2_static_tcr_public:
        M1 + dynamically generated reference-public features
    M3_static_tcr_public_material:
        M2 + material

Leakage controls:
1. The independent test set is never read.
2. Inner folds are used only inside the selected outer-training subset.
3. Dynamic public reference sets are rebuilt from the current training
   partition for every inner validation fold.
4. Dynamic public features for samples used to fit a model are generated by
   an additional stratified cross-fitting layer, so a sample never contributes
   to the reference used for its own public features.
5. Encoding, zero-variance filtering and standardization are learned only from
   the current model-training partition.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
import time
import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
from scipy import sparse
from sklearn.exceptions import ConvergenceWarning
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)


SCRIPT_VERSION = "1.0.1"

ROOT = Path("/data/users/chenhaisheng/RA-ILD/TRB")

DEFAULT_BASE = (
    ROOT / "set/train/result/04_final_feature_matrix/"
           "04_train_base_feature_matrix.csv"
)
DEFAULT_MANIFEST = (
    ROOT / "set/train/result/04_final_feature_matrix/"
           "04_feature_manifest.csv"
)
DEFAULT_OUTER = (
    ROOT / "set/train/result/05_modeling/cv_splits/"
           "05_outer_fold_assignments.csv"
)
DEFAULT_INNER = (
    ROOT / "set/train/result/05_modeling/cv_splits/"
           "05_inner_fold_assignments.csv.gz"
)
DEFAULT_CATALOG = (
    ROOT / "set/train/result/03_public_features/"
           "03_public_aa_catalog.csv.gz"
)
DEFAULT_REFERENCE_DEFINITION = (
    ROOT / "set/train/result/03_public_features/"
           "03_reference_definition.json"
)
DEFAULT_CLONE_DIR = ROOT / "set/train/result/01_AA_clone_table"
DEFAULT_CACHE_DIR = ROOT / "set/train/result/05_modeling/cache"
DEFAULT_OUTPUT_ROOT = ROOT / "set/train/result/05_modeling/single_outer_trial"


ALL_PUBLIC_FEATURES = [
    "all_ref_public_clone_number",
    "all_ref_public_clone_ratio",
    "all_ref_public_frequency_sum",
    "all_ref_public_set_coverage",
    "RA_specific_ref_clone_number",
    "RA_specific_ref_clone_ratio",
    "RA_specific_ref_frequency_sum",
    "RA_specific_ref_set_coverage",
    "ILD_specific_ref_clone_number",
    "ILD_specific_ref_clone_ratio",
    "ILD_specific_ref_frequency_sum",
    "ILD_specific_ref_set_coverage",
    "shared_ref_clone_number",
    "shared_ref_clone_ratio",
    "shared_ref_frequency_sum",
    "shared_ref_set_coverage",
    "ILD_RA_specific_ref_frequency_delta",
    "ILD_RA_specific_ref_frequency_log_ratio",
]

PUBLIC_FEATURE_SETS = {
    # Default main variant: no raw counts, no exact delta dependency,
    # no simultaneous log-ratio transformation.
    "raw_bilateral": [
        "all_ref_public_clone_ratio",
        "all_ref_public_frequency_sum",
        "shared_ref_clone_ratio",
        "shared_ref_frequency_sum",
        "RA_specific_ref_clone_ratio",
        "RA_specific_ref_frequency_sum",
        "ILD_specific_ref_clone_ratio",
        "ILD_specific_ref_frequency_sum",
    ],
    "log_ratio": [
        "all_ref_public_clone_ratio",
        "all_ref_public_frequency_sum",
        "shared_ref_clone_ratio",
        "shared_ref_frequency_sum",
        "ILD_RA_specific_ref_frequency_log_ratio",
    ],
    "all18": ALL_PUBLIC_FEATURES,
}

MODEL_LABELS = {
    "M0_clinical": "age + sex",
    "M1_static_tcr": "age + sex + static TCR",
    "M2_static_tcr_public": "age + sex + static TCR + dynamic public",
    "M3_static_tcr_public_material": (
        "age + sex + material + static TCR + dynamic public"
    ),
}


@dataclass
class PublicReference:
    global_mask: np.ndarray
    ra_specific_mask: np.ndarray
    ild_specific_mask: np.ndarray
    shared_mask: np.ndarray
    n_reference: int
    n_ra: int
    n_ild: int
    global_threshold: int
    ra_threshold: int
    ild_threshold: int


@dataclass
class PreparedFold:
    X_train: np.ndarray
    X_valid: np.ndarray
    y_train: np.ndarray
    y_valid: np.ndarray
    valid_sample_ids: List[str]
    feature_names: List[str]
    preprocess_rows: List[Dict[str, object]]


def parse_float_list(text: str) -> List[float]:
    values = [float(x.strip()) for x in text.split(",") if x.strip()]
    if not values:
        raise argparse.ArgumentTypeError("At least one numeric value is required.")
    return values


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run one leakage-controlled outer-fold Elastic Net trial.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument("--base-matrix", default=str(DEFAULT_BASE))
    parser.add_argument("--feature-manifest", default=str(DEFAULT_MANIFEST))
    parser.add_argument("--outer-assignments", default=str(DEFAULT_OUTER))
    parser.add_argument("--inner-assignments", default=str(DEFAULT_INNER))
    parser.add_argument("--public-catalog", default=str(DEFAULT_CATALOG))
    parser.add_argument(
        "--reference-definition",
        default=str(DEFAULT_REFERENCE_DEFINITION),
    )
    parser.add_argument("--clone-table-dir", default=str(DEFAULT_CLONE_DIR))
    parser.add_argument("--cache-dir", default=str(DEFAULT_CACHE_DIR))
    parser.add_argument("--output-root", default=str(DEFAULT_OUTPUT_ROOT))

    parser.add_argument("--outer-repeat", type=int, default=1)
    parser.add_argument("--outer-fold", type=int, default=1)
    parser.add_argument("--inner-folds", type=int, default=5)
    parser.add_argument("--public-crossfit-folds", type=int, default=5)

    parser.add_argument("--sample-id-col", default="sample_id")
    parser.add_argument("--label-col", default="cohort")
    parser.add_argument("--positive-label", default="ILD")
    parser.add_argument("--age-col", default="age")
    parser.add_argument("--sex-col", default="sex")
    parser.add_argument("--material-col", default="material")
    parser.add_argument("--aa-clone-number-col", default="aa_clone_number")

    parser.add_argument(
        "--clone-file-pattern",
        default="{sample_id}_TRB_CDR3_AA_clone_table.csv",
    )
    parser.add_argument("--sequence-col", default="cdr3_aa")
    parser.add_argument("--frequency-col", default="frequency_norm")

    parser.add_argument("--global-min-prevalence", type=float, default=0.02)
    parser.add_argument("--global-min-count", type=int, default=3)
    parser.add_argument("--group-min-prevalence", type=float, default=0.05)
    parser.add_argument("--group-min-count", type=int, default=3)
    parser.add_argument("--specific-prevalence-delta", type=float, default=0.05)
    parser.add_argument("--epsilon", type=float, default=1e-8)

    parser.add_argument(
        "--public-feature-set",
        choices=sorted(PUBLIC_FEATURE_SETS),
        default="raw_bilateral",
    )
    parser.add_argument(
        "--l1-ratios",
        type=parse_float_list,
        default=parse_float_list("0.1,0.5,0.9"),
    )
    parser.add_argument(
        "--lambdas",
        type=parse_float_list,
        default=parse_float_list("0.01,0.03,0.1,0.3,1,3,10,30"),
    )
    parser.add_argument(
        "--class-weight",
        choices=("balanced", "none"),
        default="balanced",
    )
    parser.add_argument("--max-iter", type=int, default=10000)
    parser.add_argument("--tolerance", type=float, default=1e-4)
    parser.add_argument("--zero-sd-tolerance", type=float, default=1e-12)
    parser.add_argument("--seed", type=int, default=20260711)

    parser.add_argument("--expected-samples", type=int, default=123)
    parser.add_argument("--expected-catalog-size", type=int, default=1000139)
    parser.add_argument("--expected-global-size", type=int, default=394235)
    parser.add_argument("--expected-ra-specific-size", type=int, default=41649)
    parser.add_argument("--expected-ild-specific-size", type=int, default=28947)
    parser.add_argument("--expected-shared-size", type=int, default=38585)
    parser.add_argument(
        "--skip-full-reference-validation",
        action="store_true",
    )
    parser.add_argument("--force-rebuild-cache", action="store_true")
    parser.add_argument("--overwrite", action="store_true")

    args = parser.parse_args()

    for x in args.l1_ratios:
        if not (0 < x <= 1):
            parser.error("Every l1 ratio must be in (0, 1].")
    for x in args.lambdas:
        if x <= 0:
            parser.error("Every lambda must be > 0.")
    if args.public_crossfit_folds < 2:
        parser.error("--public-crossfit-folds must be >= 2.")
    return args


def sha256sum(path: Path, chunk_size: int = 1024 * 1024) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(chunk_size)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def derive_seed(base_seed: int, *parts: int) -> int:
    text = ":".join(str(x) for x in (base_seed, *parts))
    return int.from_bytes(
        hashlib.sha256(text.encode("utf-8")).digest()[:8],
        "little",
    ) % (2**32 - 1)


def ensure_file(path: Path, label: str) -> None:
    if not path.is_file():
        raise FileNotFoundError(f"{label} not found: {path}")


def ensure_no_missing(df: pd.DataFrame, label: str) -> None:
    n = int(df.isna().sum().sum())
    if n:
        cols = df.isna().sum()
        bad = cols[cols > 0].sort_values(ascending=False).head(20)
        raise ValueError(f"{label} has {n} missing values: {bad.to_dict()}")


def read_core_inputs(args: argparse.Namespace):
    base_path = Path(args.base_matrix).expanduser().resolve()
    manifest_path = Path(args.feature_manifest).expanduser().resolve()
    outer_path = Path(args.outer_assignments).expanduser().resolve()
    inner_path = Path(args.inner_assignments).expanduser().resolve()

    for p, label in [
        (base_path, "base matrix"),
        (manifest_path, "feature manifest"),
        (outer_path, "outer assignments"),
        (inner_path, "inner assignments"),
    ]:
        ensure_file(p, label)

    base = pd.read_csv(base_path)
    manifest = pd.read_csv(manifest_path)
    outer = pd.read_csv(outer_path)
    inner = pd.read_csv(inner_path)

    required_base = {
        args.sample_id_col,
        args.label_col,
        args.age_col,
        args.sex_col,
        args.material_col,
        args.aa_clone_number_col,
    }
    missing = required_base - set(base.columns)
    if missing:
        raise ValueError(f"Base matrix missing columns: {sorted(missing)}")
    if base[args.sample_id_col].duplicated().any():
        raise ValueError("Base matrix has duplicated sample IDs.")
    ensure_no_missing(base, "base matrix")

    base[args.sample_id_col] = base[args.sample_id_col].astype(str)
    base[args.label_col] = base[args.label_col].astype(str).str.upper()

    if args.expected_samples > 0 and len(base) != args.expected_samples:
        raise ValueError(
            f"Expected {args.expected_samples} base samples, observed {len(base)}."
        )

    outer_task = outer[outer["outer_repeat"] == args.outer_repeat].copy()
    if len(outer_task) != len(base):
        raise ValueError(
            f"Outer repeat {args.outer_repeat} has {len(outer_task)} rows, "
            f"expected {len(base)}."
        )
    if set(outer_task[args.sample_id_col].astype(str)) != set(
        base[args.sample_id_col]
    ):
        raise ValueError("Outer assignment sample IDs do not match base matrix.")

    outer_train_ids = set(
        outer_task.loc[
            outer_task["outer_fold"] != args.outer_fold,
            args.sample_id_col,
        ].astype(str)
    )
    outer_valid_ids = set(
        outer_task.loc[
            outer_task["outer_fold"] == args.outer_fold,
            args.sample_id_col,
        ].astype(str)
    )
    if outer_train_ids & outer_valid_ids:
        raise ValueError("Outer training and validation IDs overlap.")
    if outer_train_ids | outer_valid_ids != set(base[args.sample_id_col]):
        raise ValueError("Outer task does not cover all base samples.")

    inner_task = inner[
        (inner["outer_repeat"] == args.outer_repeat)
        & (inner["outer_fold"] == args.outer_fold)
    ].copy()
    inner_task[args.sample_id_col] = inner_task[args.sample_id_col].astype(str)

    if set(inner_task[args.sample_id_col]) != outer_train_ids:
        raise ValueError(
            "Inner assignment IDs are not exactly the selected outer-training IDs."
        )
    if inner_task[args.sample_id_col].duplicated().any():
        raise ValueError("Inner assignment contains duplicated sample IDs.")
    if set(inner_task["inner_fold"]) != set(range(1, args.inner_folds + 1)):
        raise ValueError("Inner assignment does not contain all requested folds.")
    if set(inner_task[args.sample_id_col]) & outer_valid_ids:
        raise ValueError("Outer validation samples leaked into inner assignments.")

    base = base.set_index(args.sample_id_col, drop=False)
    outer_train_order = [
        x for x in base.index.tolist() if x in outer_train_ids
    ]
    outer_valid_order = [
        x for x in base.index.tolist() if x in outer_valid_ids
    ]

    return (
        base,
        manifest,
        outer_task,
        inner_task,
        outer_train_order,
        outer_valid_order,
        {
            "base": base_path,
            "manifest": manifest_path,
            "outer": outer_path,
            "inner": inner_path,
        },
    )


def static_tcr_features_from_manifest(
    manifest: pd.DataFrame,
    base: pd.DataFrame,
) -> List[str]:
    required = {
        "feature_name",
        "present_in_train_base",
        "feature_group",
        "feature_role",
        "reference_drop",
    }
    missing = required - set(manifest.columns)
    if missing:
        raise ValueError(f"Feature manifest missing columns: {sorted(missing)}")

    def as_bool(series: pd.Series) -> pd.Series:
        if pd.api.types.is_bool_dtype(series):
            return series
        return series.astype(str).str.lower().isin({"true", "1", "yes"})

    present = as_bool(manifest["present_in_train_base"])
    ref_drop = as_bool(manifest["reference_drop"])

    selected = manifest.loc[
        present
        & manifest["feature_group"].astype(str).str.startswith("tcr_")
        & manifest["feature_role"].astype(str).eq("candidate_predictor")
        & (~ref_drop),
        "feature_name",
    ].astype(str).tolist()

    selected = [x for x in selected if x in base.columns]
    if not selected:
        raise ValueError("No static TCR features were selected from the manifest.")
    if len(selected) != len(set(selected)):
        raise ValueError("Static TCR feature list contains duplicates.")
    return selected


def cache_paths(cache_dir: Path) -> Dict[str, Path]:
    return {
        "presence": cache_dir / "05_train_public_presence.npz",
        "frequency": cache_dir / "05_train_public_frequency.npz",
        "metadata": cache_dir / "05_train_public_sparse_cache.json",
    }


def source_file_signature(
    sample_ids: Sequence[str],
    clone_dir: Path,
    pattern: str,
) -> List[Dict[str, object]]:
    rows = []
    for sample_id in sample_ids:
        path = clone_dir / pattern.format(sample_id=sample_id)
        ensure_file(path, f"clone table for {sample_id}")
        stat = path.stat()
        rows.append({
            "sample_id": sample_id,
            "path": str(path),
            "size": stat.st_size,
            "mtime_ns": stat.st_mtime_ns,
        })
    return rows


def cache_matches(
    metadata_path: Path,
    sample_ids: Sequence[str],
    catalog_path: Path,
    clone_signatures: Sequence[Mapping[str, object]],
) -> bool:
    if not metadata_path.is_file():
        return False
    try:
        meta = json.loads(metadata_path.read_text(encoding="utf-8"))
    except Exception:
        return False
    return (
        meta.get("sample_ids") == list(sample_ids)
        and meta.get("catalog_sha256") == sha256sum(catalog_path)
        and meta.get("clone_files") == list(clone_signatures)
    )


def build_or_load_sparse_cache(
    args: argparse.Namespace,
    base: pd.DataFrame,
) -> Tuple[sparse.csr_matrix, sparse.csr_matrix, Dict[str, object]]:
    catalog_path = Path(args.public_catalog).expanduser().resolve()
    clone_dir = Path(args.clone_table_dir).expanduser().resolve()
    cache_dir = Path(args.cache_dir).expanduser().resolve()
    ensure_file(catalog_path, "public AA catalog")
    if not clone_dir.is_dir():
        raise FileNotFoundError(f"Clone table directory not found: {clone_dir}")
    cache_dir.mkdir(parents=True, exist_ok=True)

    paths = cache_paths(cache_dir)
    sample_ids = base.index.astype(str).tolist()
    clone_signatures = source_file_signature(
        sample_ids, clone_dir, args.clone_file_pattern
    )

    valid_cache = (
        not args.force_rebuild_cache
        and paths["presence"].is_file()
        and paths["frequency"].is_file()
        and cache_matches(
            paths["metadata"],
            sample_ids,
            catalog_path,
            clone_signatures,
        )
    )

    if valid_cache:
        presence = sparse.load_npz(paths["presence"]).tocsr()
        frequency = sparse.load_npz(paths["frequency"]).tocsr()
        meta = json.loads(paths["metadata"].read_text(encoding="utf-8"))
        if presence.shape != frequency.shape:
            raise ValueError("Cached presence/frequency shapes differ.")
        if presence.shape[0] != len(sample_ids):
            raise ValueError("Cached matrix row count differs from base matrix.")
        return presence, frequency, meta

    catalog = pd.read_csv(catalog_path, usecols=[args.sequence_col])
    catalog[args.sequence_col] = catalog[args.sequence_col].astype(str)
    if catalog[args.sequence_col].duplicated().any():
        raise ValueError("Public AA catalog contains duplicated sequences.")
    if (
        args.expected_catalog_size > 0
        and len(catalog) != args.expected_catalog_size
    ):
        raise ValueError(
            f"Expected catalog size {args.expected_catalog_size}, "
            f"observed {len(catalog)}."
        )

    sequence_to_col = {
        seq: i for i, seq in enumerate(catalog[args.sequence_col].tolist())
    }

    row_parts: List[np.ndarray] = []
    col_parts: List[np.ndarray] = []
    freq_parts: List[np.ndarray] = []
    observed_clone_counts: Dict[str, int] = {}

    for row_idx, sample_id in enumerate(sample_ids):
        path = clone_dir / args.clone_file_pattern.format(sample_id=sample_id)
        clone = pd.read_csv(
            path,
            usecols=[args.sequence_col, args.frequency_col],
        )
        if clone[args.sequence_col].duplicated().any():
            raise ValueError(f"{sample_id} clone table has duplicated AA sequences.")
        clone[args.sequence_col] = clone[args.sequence_col].astype(str)
        clone[args.frequency_col] = pd.to_numeric(
            clone[args.frequency_col], errors="raise"
        )
        if (clone[args.frequency_col] < 0).any():
            raise ValueError(f"{sample_id} has negative frequency_norm.")
        observed_clone_counts[sample_id] = len(clone)

        expected_aa = int(round(float(base.loc[sample_id, args.aa_clone_number_col])))
        if expected_aa != len(clone):
            raise ValueError(
                f"{sample_id}: aa_clone_number={expected_aa}, "
                f"01 rows={len(clone)}."
            )

        mapped = clone[args.sequence_col].map(sequence_to_col)
        keep = mapped.notna().to_numpy()
        cols = mapped[keep].astype(np.int64).to_numpy()
        values = clone.loc[keep, args.frequency_col].to_numpy(dtype=np.float64)

        row_parts.append(np.full(len(cols), row_idx, dtype=np.int32))
        col_parts.append(cols)
        freq_parts.append(values)

        if row_idx == 0 or (row_idx + 1) % 20 == 0 or row_idx + 1 == len(sample_ids):
            print(
                f"[sparse cache] processed {row_idx + 1}/{len(sample_ids)} samples"
            )

    rows = np.concatenate(row_parts) if row_parts else np.array([], dtype=np.int32)
    cols = np.concatenate(col_parts) if col_parts else np.array([], dtype=np.int64)
    freq_values = (
        np.concatenate(freq_parts)
        if freq_parts
        else np.array([], dtype=np.float64)
    )

    shape = (len(sample_ids), len(catalog))
    presence = sparse.csr_matrix(
        (np.ones(len(rows), dtype=np.uint8), (rows, cols)),
        shape=shape,
    )
    frequency = sparse.csr_matrix(
        (freq_values, (rows, cols)),
        shape=shape,
    )
    presence.sum_duplicates()
    frequency.sum_duplicates()

    sparse.save_npz(paths["presence"], presence, compressed=True)
    sparse.save_npz(paths["frequency"], frequency, compressed=True)

    meta = {
        "script_version": SCRIPT_VERSION,
        "sample_ids": sample_ids,
        "catalog_path": str(catalog_path),
        "catalog_sha256": sha256sum(catalog_path),
        "catalog_size": len(catalog),
        "matrix_shape": list(shape),
        "presence_nnz": int(presence.nnz),
        "frequency_nnz": int(frequency.nnz),
        "clone_files": clone_signatures,
        "observed_clone_counts": observed_clone_counts,
    }
    paths["metadata"].write_text(
        json.dumps(meta, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return presence, frequency, meta


def effective_threshold(n: int, prevalence: float, minimum: int) -> int:
    return max(minimum, int(math.ceil(prevalence * n)))


def build_public_reference(
    presence: sparse.csr_matrix,
    reference_rows: np.ndarray,
    labels: np.ndarray,
    args: argparse.Namespace,
) -> PublicReference:
    reference_rows = np.asarray(reference_rows, dtype=int)
    ref_labels = labels[reference_rows]
    ra_rows = reference_rows[ref_labels == "RA"]
    ild_rows = reference_rows[ref_labels == "ILD"]

    if len(ra_rows) < args.group_min_count:
        raise ValueError("Too few RA reference samples.")
    if len(ild_rows) < args.group_min_count:
        raise ValueError("Too few ILD reference samples.")

    total_counts = np.asarray(
        presence[reference_rows].sum(axis=0)
    ).ravel()
    ra_counts = np.asarray(presence[ra_rows].sum(axis=0)).ravel()
    ild_counts = np.asarray(presence[ild_rows].sum(axis=0)).ravel()

    global_threshold = effective_threshold(
        len(reference_rows),
        args.global_min_prevalence,
        args.global_min_count,
    )
    ra_threshold = effective_threshold(
        len(ra_rows),
        args.group_min_prevalence,
        args.group_min_count,
    )
    ild_threshold = effective_threshold(
        len(ild_rows),
        args.group_min_prevalence,
        args.group_min_count,
    )

    global_mask = total_counts >= global_threshold
    ra_group = ra_counts >= ra_threshold
    ild_group = ild_counts >= ild_threshold

    ra_prevalence = ra_counts / len(ra_rows)
    ild_prevalence = ild_counts / len(ild_rows)

    ra_specific_mask = (
        ra_group
        & ((ra_prevalence - ild_prevalence) >= args.specific_prevalence_delta)
    )
    ild_specific_mask = (
        ild_group
        & ((ild_prevalence - ra_prevalence) >= args.specific_prevalence_delta)
    )

    # Keep shared mutually exclusive from the two group-specific sets.
    # This exactly matches step-03 public_feature_utils.build_reference_masks().
    shared_mask = (
        ra_group
        & ild_group
        & ~ra_specific_mask
        & ~ild_specific_mask
    )

    return PublicReference(
        global_mask=global_mask,
        ra_specific_mask=ra_specific_mask,
        ild_specific_mask=ild_specific_mask,
        shared_mask=shared_mask,
        n_reference=len(reference_rows),
        n_ra=len(ra_rows),
        n_ild=len(ild_rows),
        global_threshold=global_threshold,
        ra_threshold=ra_threshold,
        ild_threshold=ild_threshold,
    )


def reference_summary_row(
    ref: PublicReference,
    context: str,
    outer_repeat: int,
    outer_fold: int,
    inner_fold: Optional[int] = None,
    crossfit_fold: Optional[int] = None,
) -> Dict[str, object]:
    return {
        "context": context,
        "outer_repeat": outer_repeat,
        "outer_fold": outer_fold,
        "inner_fold": inner_fold if inner_fold is not None else "",
        "crossfit_fold": crossfit_fold if crossfit_fold is not None else "",
        "n_reference": ref.n_reference,
        "n_RA_reference": ref.n_ra,
        "n_ILD_reference": ref.n_ild,
        "global_threshold": ref.global_threshold,
        "RA_threshold": ref.ra_threshold,
        "ILD_threshold": ref.ild_threshold,
        "all_ref_public_size": int(ref.global_mask.sum()),
        "RA_specific_ref_size": int(ref.ra_specific_mask.sum()),
        "ILD_specific_ref_size": int(ref.ild_specific_mask.sum()),
        "shared_ref_size": int(ref.shared_mask.sum()),
    }


def apply_public_reference(
    presence: sparse.csr_matrix,
    frequency: sparse.csr_matrix,
    target_rows: np.ndarray,
    aa_clone_numbers: np.ndarray,
    ref: PublicReference,
    epsilon: float,
) -> pd.DataFrame:
    target_rows = np.asarray(target_rows, dtype=int)
    target_presence = presence[target_rows]
    target_frequency = frequency[target_rows]

    result: Dict[str, np.ndarray] = {}

    masks = {
        "all_ref_public": ref.global_mask,
        "RA_specific_ref": ref.ra_specific_mask,
        "ILD_specific_ref": ref.ild_specific_mask,
        "shared_ref": ref.shared_mask,
    }

    for prefix, mask in masks.items():
        set_size = int(mask.sum())
        clone_number = np.asarray(
            target_presence[:, mask].sum(axis=1)
        ).ravel().astype(float)
        frequency_sum = np.asarray(
            target_frequency[:, mask].sum(axis=1)
        ).ravel().astype(float)

        result[f"{prefix}_clone_number"] = clone_number
        result[f"{prefix}_clone_ratio"] = np.divide(
            clone_number,
            aa_clone_numbers[target_rows],
            out=np.zeros_like(clone_number, dtype=float),
            where=aa_clone_numbers[target_rows] > 0,
        )
        result[f"{prefix}_frequency_sum"] = frequency_sum
        result[f"{prefix}_set_coverage"] = (
            clone_number / set_size if set_size > 0 else np.zeros_like(clone_number)
        )

    ild_sum = result["ILD_specific_ref_frequency_sum"]
    ra_sum = result["RA_specific_ref_frequency_sum"]
    result["ILD_RA_specific_ref_frequency_delta"] = ild_sum - ra_sum
    result["ILD_RA_specific_ref_frequency_log_ratio"] = np.log(
        (ild_sum + epsilon) / (ra_sum + epsilon)
    )

    out = pd.DataFrame(result)
    return out[ALL_PUBLIC_FEATURES]


def stratified_assignment(
    labels: np.ndarray,
    n_folds: int,
    seed: int,
) -> np.ndarray:
    if min(np.sum(labels == label) for label in np.unique(labels)) < n_folds:
        raise ValueError(
            f"Cannot make {n_folds} stratified folds: "
            f"class counts={dict(zip(*np.unique(labels, return_counts=True)))}"
        )
    rng = np.random.default_rng(seed)
    assignment = np.full(len(labels), -1, dtype=int)
    for label in sorted(np.unique(labels)):
        idx = np.flatnonzero(labels == label)
        shuffled = rng.permutation(idx)
        offset = int(rng.integers(0, n_folds))
        assignment[shuffled] = (
            (np.arange(len(shuffled)) + offset) % n_folds
        ) + 1
    return assignment


def crossfit_public_features(
    presence: sparse.csr_matrix,
    frequency: sparse.csr_matrix,
    sample_rows: np.ndarray,
    labels: np.ndarray,
    aa_clone_numbers: np.ndarray,
    n_folds: int,
    seed: int,
    args: argparse.Namespace,
    context: str,
    inner_fold: Optional[int],
    reference_rows_log: List[Dict[str, object]],
    crossfit_assignment_log: List[Dict[str, object]],
) -> pd.DataFrame:
    sample_rows = np.asarray(sample_rows, dtype=int)
    local_labels = labels[sample_rows]
    assignment = stratified_assignment(local_labels, n_folds, seed)

    output = pd.DataFrame(
        index=sample_rows,
        columns=ALL_PUBLIC_FEATURES,
        dtype=float,
    )

    for fold in range(1, n_folds + 1):
        held_local = np.flatnonzero(assignment == fold)
        ref_local = np.flatnonzero(assignment != fold)
        held_rows = sample_rows[held_local]
        ref_rows = sample_rows[ref_local]

        ref = build_public_reference(
            presence, ref_rows, labels, args
        )
        values = apply_public_reference(
            presence,
            frequency,
            held_rows,
            aa_clone_numbers,
            ref,
            args.epsilon,
        )
        values.index = held_rows
        output.loc[held_rows, ALL_PUBLIC_FEATURES] = values

        reference_rows_log.append(
            reference_summary_row(
                ref,
                context=context,
                outer_repeat=args.outer_repeat,
                outer_fold=args.outer_fold,
                inner_fold=inner_fold,
                crossfit_fold=fold,
            )
        )
        for row in held_rows:
            crossfit_assignment_log.append({
                "context": context,
                "outer_repeat": args.outer_repeat,
                "outer_fold": args.outer_fold,
                "inner_fold": inner_fold if inner_fold is not None else "",
                "crossfit_fold": fold,
                "row_index": int(row),
            })

    if output.isna().any().any():
        raise RuntimeError(f"Missing cross-fitted public values in {context}.")
    return output.sort_index()


def external_public_features(
    presence: sparse.csr_matrix,
    frequency: sparse.csr_matrix,
    reference_rows: np.ndarray,
    target_rows: np.ndarray,
    labels: np.ndarray,
    aa_clone_numbers: np.ndarray,
    args: argparse.Namespace,
    context: str,
    inner_fold: Optional[int],
    reference_rows_log: List[Dict[str, object]],
) -> pd.DataFrame:
    ref = build_public_reference(
        presence, reference_rows, labels, args
    )
    values = apply_public_reference(
        presence,
        frequency,
        target_rows,
        aa_clone_numbers,
        ref,
        args.epsilon,
    )
    values.index = np.asarray(target_rows, dtype=int)
    reference_rows_log.append(
        reference_summary_row(
            ref,
            context=context,
            outer_repeat=args.outer_repeat,
            outer_fold=args.outer_fold,
            inner_fold=inner_fold,
        )
    )
    return values.sort_index()


def validate_full_reference(
    presence: sparse.csr_matrix,
    labels: np.ndarray,
    args: argparse.Namespace,
) -> Dict[str, int]:
    ref = build_public_reference(
        presence,
        np.arange(presence.shape[0], dtype=int),
        labels,
        args,
    )
    observed = {
        "global": int(ref.global_mask.sum()),
        "RA_specific": int(ref.ra_specific_mask.sum()),
        "ILD_specific": int(ref.ild_specific_mask.sum()),
        "shared": int(ref.shared_mask.sum()),
    }
    expected = {
        "global": args.expected_global_size,
        "RA_specific": args.expected_ra_specific_size,
        "ILD_specific": args.expected_ild_specific_size,
        "shared": args.expected_shared_size,
    }
    for key, exp in expected.items():
        if exp > 0 and observed[key] != exp:
            raise ValueError(
                "Dynamic public definition does not reproduce step-03. "
                f"{key}: expected {exp}, observed {observed[key]}."
            )
    return observed


def build_design(
    train_df: pd.DataFrame,
    valid_df: pd.DataFrame,
    numeric_cols: Sequence[str],
    categorical_cols: Sequence[str],
    zero_sd_tolerance: float,
) -> Tuple[np.ndarray, np.ndarray, List[str], List[Dict[str, object]]]:
    train_parts: List[np.ndarray] = []
    valid_parts: List[np.ndarray] = []
    feature_names: List[str] = []
    source_types: List[str] = []

    for col in numeric_cols:
        train_values = pd.to_numeric(train_df[col], errors="raise").to_numpy(float)
        valid_values = pd.to_numeric(valid_df[col], errors="raise").to_numpy(float)
        train_parts.append(train_values[:, None])
        valid_parts.append(valid_values[:, None])
        feature_names.append(col)
        source_types.append("numeric")

    for col in categorical_cols:
        train_values = train_df[col].astype(str)
        valid_values = valid_df[col].astype(str)
        categories = sorted(train_values.unique().tolist())
        if not categories:
            raise ValueError(f"No training category found for {col}.")
        reference = categories[0]
        for category in categories[1:]:
            train_parts.append((train_values == category).to_numpy(float)[:, None])
            valid_parts.append((valid_values == category).to_numpy(float)[:, None])
            feature_names.append(f"{col}__{category}_vs_{reference}")
            source_types.append("categorical_dummy")

    if not train_parts:
        raise ValueError("No predictor columns were assembled.")

    X_train_raw = np.hstack(train_parts)
    X_valid_raw = np.hstack(valid_parts)

    means = X_train_raw.mean(axis=0)
    sds = X_train_raw.std(axis=0, ddof=0)
    keep = np.isfinite(sds) & (sds > zero_sd_tolerance)

    if not keep.any():
        raise ValueError("All predictors had zero/invalid standard deviation.")

    X_train = (X_train_raw[:, keep] - means[keep]) / sds[keep]
    X_valid = (X_valid_raw[:, keep] - means[keep]) / sds[keep]
    kept_names = [name for name, flag in zip(feature_names, keep) if flag]

    rows: List[Dict[str, object]] = []
    for name, source_type, mean, sd, flag in zip(
        feature_names, source_types, means, sds, keep
    ):
        rows.append({
            "feature_name": name,
            "source_type": source_type,
            "training_mean": float(mean),
            "training_sd": float(sd),
            "kept_after_zero_variance_filter": bool(flag),
        })

    if not np.isfinite(X_train).all() or not np.isfinite(X_valid).all():
        raise ValueError("Non-finite values were produced during preprocessing.")
    return X_train, X_valid, kept_names, rows


def model_specifications(
    static_features: Sequence[str],
    public_features: Sequence[str],
    args: argparse.Namespace,
) -> Dict[str, Dict[str, List[str]]]:
    static_numeric = [args.age_col, *static_features]
    public_numeric = [*static_numeric, *public_features]

    return {
        "M0_clinical": {
            "numeric": [args.age_col],
            "categorical": [args.sex_col],
        },
        "M1_static_tcr": {
            "numeric": static_numeric,
            "categorical": [args.sex_col],
        },
        "M2_static_tcr_public": {
            "numeric": public_numeric,
            "categorical": [args.sex_col],
        },
        "M3_static_tcr_public_material": {
            "numeric": public_numeric,
            "categorical": [args.sex_col, args.material_col],
        },
    }


def fit_elastic_net(
    X: np.ndarray,
    y: np.ndarray,
    l1_ratio: float,
    lambda_value: float,
    args: argparse.Namespace,
    seed: int,
) -> Tuple[LogisticRegression, bool, int]:
    class_weight = None if args.class_weight == "none" else args.class_weight
    model = LogisticRegression(
        penalty="elasticnet",
        solver="saga",
        l1_ratio=l1_ratio,
        C=1.0 / lambda_value,
        class_weight=class_weight,
        max_iter=args.max_iter,
        tol=args.tolerance,
        random_state=seed,
        fit_intercept=True,
    )
    converged = True
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always", ConvergenceWarning)
        model.fit(X, y)
        converged = not any(
            issubclass(w.category, ConvergenceWarning) for w in caught
        )
    n_iter = int(np.max(model.n_iter_))
    return model, converged, n_iter


def safe_auc(y: np.ndarray, probability: np.ndarray) -> float:
    return float(roc_auc_score(y, probability))


def choose_threshold_youden(
    y: np.ndarray,
    probability: np.ndarray,
) -> float:
    fpr, tpr, thresholds = roc_curve(y, probability)
    finite = np.isfinite(thresholds)
    if not finite.any():
        return 0.5
    j = tpr[finite] - fpr[finite]
    candidates = thresholds[finite][j == np.max(j)]
    return float(candidates[np.argmin(np.abs(candidates - 0.5))])


def classification_metrics(
    y: np.ndarray,
    probability: np.ndarray,
    threshold: float,
) -> Dict[str, float]:
    pred = (probability >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y, pred, labels=[0, 1]).ravel()
    specificity = tn / (tn + fp) if tn + fp else np.nan
    return {
        "roc_auc": safe_auc(y, probability),
        "pr_auc": float(average_precision_score(y, probability)),
        "threshold": float(threshold),
        "accuracy": float(accuracy_score(y, pred)),
        "sensitivity_recall": float(recall_score(y, pred, zero_division=0)),
        "specificity": float(specificity),
        "precision": float(precision_score(y, pred, zero_division=0)),
        "f1": float(f1_score(y, pred, zero_division=0)),
        "TN": int(tn),
        "FP": int(fp),
        "FN": int(fn),
        "TP": int(tp),
    }


def assemble_model_dataframe(
    base: pd.DataFrame,
    sample_ids: Sequence[str],
    public_values: Optional[pd.DataFrame],
    row_lookup: Mapping[str, int],
) -> pd.DataFrame:
    out = base.loc[list(sample_ids)].copy()
    if public_values is not None:
        row_ids = [row_lookup[sample_id] for sample_id in sample_ids]
        aligned = public_values.loc[row_ids].copy()
        aligned.index = list(sample_ids)
        for col in ALL_PUBLIC_FEATURES:
            out[col] = aligned[col].to_numpy(float)
    return out


def prepare_inner_folds(
    base: pd.DataFrame,
    inner_task: pd.DataFrame,
    outer_train_ids: Sequence[str],
    row_lookup: Mapping[str, int],
    presence: sparse.csr_matrix,
    frequency: sparse.csr_matrix,
    labels: np.ndarray,
    aa_clone_numbers: np.ndarray,
    model_specs: Mapping[str, Mapping[str, List[str]]],
    args: argparse.Namespace,
    reference_rows_log: List[Dict[str, object]],
    crossfit_assignment_log: List[Dict[str, object]],
) -> Dict[str, Dict[int, PreparedFold]]:
    prepared: Dict[str, Dict[int, PreparedFold]] = {
        model: {} for model in model_specs
    }

    for inner_fold in range(1, args.inner_folds + 1):
        valid_ids = inner_task.loc[
            inner_task["inner_fold"] == inner_fold,
            args.sample_id_col,
        ].astype(str).tolist()
        valid_set = set(valid_ids)
        train_ids = [x for x in outer_train_ids if x not in valid_set]

        train_rows = np.array([row_lookup[x] for x in train_ids], dtype=int)
        valid_rows = np.array([row_lookup[x] for x in valid_ids], dtype=int)

        train_public = crossfit_public_features(
            presence=presence,
            frequency=frequency,
            sample_rows=train_rows,
            labels=labels,
            aa_clone_numbers=aa_clone_numbers,
            n_folds=args.public_crossfit_folds,
            seed=derive_seed(
                args.seed, 100, args.outer_repeat, args.outer_fold, inner_fold
            ),
            args=args,
            context="inner_training_crossfit",
            inner_fold=inner_fold,
            reference_rows_log=reference_rows_log,
            crossfit_assignment_log=crossfit_assignment_log,
        )
        valid_public = external_public_features(
            presence=presence,
            frequency=frequency,
            reference_rows=train_rows,
            target_rows=valid_rows,
            labels=labels,
            aa_clone_numbers=aa_clone_numbers,
            args=args,
            context="inner_validation_application",
            inner_fold=inner_fold,
            reference_rows_log=reference_rows_log,
        )

        train_with_public = assemble_model_dataframe(
            base, train_ids, train_public, row_lookup
        )
        valid_with_public = assemble_model_dataframe(
            base, valid_ids, valid_public, row_lookup
        )

        y_train = (
            train_with_public[args.label_col].astype(str).str.upper()
            == args.positive_label.upper()
        ).astype(int).to_numpy()
        y_valid = (
            valid_with_public[args.label_col].astype(str).str.upper()
            == args.positive_label.upper()
        ).astype(int).to_numpy()

        for model_name, spec in model_specs.items():
            X_train, X_valid, names, prep_rows = build_design(
                train_with_public,
                valid_with_public,
                numeric_cols=spec["numeric"],
                categorical_cols=spec["categorical"],
                zero_sd_tolerance=args.zero_sd_tolerance,
            )
            for row in prep_rows:
                row.update({
                    "stage": "inner",
                    "model": model_name,
                    "inner_fold": inner_fold,
                })
            prepared[model_name][inner_fold] = PreparedFold(
                X_train=X_train,
                X_valid=X_valid,
                y_train=y_train,
                y_valid=y_valid,
                valid_sample_ids=valid_ids,
                feature_names=names,
                preprocess_rows=prep_rows,
            )
    return prepared


def tune_models(
    prepared: Mapping[str, Mapping[int, PreparedFold]],
    args: argparse.Namespace,
) -> Tuple[pd.DataFrame, pd.DataFrame, Dict[str, Dict[str, float]]]:
    tuning_rows: List[Dict[str, object]] = []
    prediction_cache: Dict[
        Tuple[str, float, float], List[Dict[str, object]]
    ] = {}

    for model_idx, model_name in enumerate(prepared):
        for l1_ratio in args.l1_ratios:
            for lambda_value in args.lambdas:
                pred_rows: List[Dict[str, object]] = []
                fold_aucs: List[float] = []
                convergence: List[bool] = []
                iterations: List[int] = []

                for inner_fold, fold_data in prepared[model_name].items():
                    model, converged, n_iter = fit_elastic_net(
                        fold_data.X_train,
                        fold_data.y_train,
                        l1_ratio=l1_ratio,
                        lambda_value=lambda_value,
                        args=args,
                        seed=derive_seed(
                            args.seed,
                            200,
                            model_idx,
                            inner_fold,
                            int(round(l1_ratio * 1000)),
                            int(round(lambda_value * 1000)),
                        ),
                    )
                    probability = model.predict_proba(fold_data.X_valid)[:, 1]
                    fold_aucs.append(
                        safe_auc(fold_data.y_valid, probability)
                    )
                    convergence.append(converged)
                    iterations.append(n_iter)

                    for sample_id, y, prob in zip(
                        fold_data.valid_sample_ids,
                        fold_data.y_valid,
                        probability,
                    ):
                        pred_rows.append({
                            "model": model_name,
                            "inner_fold": inner_fold,
                            "sample_id": sample_id,
                            "true_label": int(y),
                            "probability": float(prob),
                            "l1_ratio_alpha": l1_ratio,
                            "lambda": lambda_value,
                        })

                pred_df = pd.DataFrame(pred_rows)
                pooled_auc = safe_auc(
                    pred_df["true_label"].to_numpy(),
                    pred_df["probability"].to_numpy(),
                )
                pooled_pr = float(
                    average_precision_score(
                        pred_df["true_label"],
                        pred_df["probability"],
                    )
                )
                tuning_rows.append({
                    "model": model_name,
                    "l1_ratio_alpha": l1_ratio,
                    "lambda": lambda_value,
                    "C_inverse_lambda": 1.0 / lambda_value,
                    "pooled_inner_roc_auc": pooled_auc,
                    "pooled_inner_pr_auc": pooled_pr,
                    "mean_fold_roc_auc": float(np.mean(fold_aucs)),
                    "sd_fold_roc_auc": float(np.std(fold_aucs, ddof=1)),
                    "all_fits_converged": bool(all(convergence)),
                    "max_iterations_used": int(max(iterations)),
                })
                prediction_cache[
                    (model_name, l1_ratio, lambda_value)
                ] = pred_rows

    tuning = pd.DataFrame(tuning_rows)

    selected: Dict[str, Dict[str, float]] = {}
    selected_oof_parts: List[pd.DataFrame] = []

    for model_name in prepared:
        candidates = tuning[tuning["model"] == model_name].copy()
        candidates = candidates.sort_values(
            [
                "pooled_inner_roc_auc",
                "pooled_inner_pr_auc",
                "lambda",
                "l1_ratio_alpha",
            ],
            ascending=[False, False, False, False],
        )
        best = candidates.iloc[0]
        l1_ratio = float(best["l1_ratio_alpha"])
        lambda_value = float(best["lambda"])
        pred = pd.DataFrame(
            prediction_cache[(model_name, l1_ratio, lambda_value)]
        )
        threshold = choose_threshold_youden(
            pred["true_label"].to_numpy(),
            pred["probability"].to_numpy(),
        )
        pred["selected_threshold"] = threshold
        selected_oof_parts.append(pred)
        selected[model_name] = {
            "l1_ratio": l1_ratio,
            "lambda": lambda_value,
            "threshold": threshold,
            "inner_roc_auc": float(best["pooled_inner_roc_auc"]),
            "inner_pr_auc": float(best["pooled_inner_pr_auc"]),
        }

    selected_oof = pd.concat(selected_oof_parts, ignore_index=True)
    return tuning, selected_oof, selected


def fit_outer_models(
    base: pd.DataFrame,
    outer_train_ids: Sequence[str],
    outer_valid_ids: Sequence[str],
    row_lookup: Mapping[str, int],
    presence: sparse.csr_matrix,
    frequency: sparse.csr_matrix,
    labels: np.ndarray,
    aa_clone_numbers: np.ndarray,
    model_specs: Mapping[str, Mapping[str, List[str]]],
    selected: Mapping[str, Mapping[str, float]],
    args: argparse.Namespace,
    reference_rows_log: List[Dict[str, object]],
    crossfit_assignment_log: List[Dict[str, object]],
) -> Tuple[
    pd.DataFrame,
    pd.DataFrame,
    pd.DataFrame,
    pd.DataFrame,
    pd.DataFrame,
    pd.DataFrame,
]:
    train_rows = np.array([row_lookup[x] for x in outer_train_ids], dtype=int)
    valid_rows = np.array([row_lookup[x] for x in outer_valid_ids], dtype=int)

    train_public = crossfit_public_features(
        presence=presence,
        frequency=frequency,
        sample_rows=train_rows,
        labels=labels,
        aa_clone_numbers=aa_clone_numbers,
        n_folds=args.public_crossfit_folds,
        seed=derive_seed(
            args.seed, 300, args.outer_repeat, args.outer_fold
        ),
        args=args,
        context="outer_training_crossfit",
        inner_fold=None,
        reference_rows_log=reference_rows_log,
        crossfit_assignment_log=crossfit_assignment_log,
    )
    valid_public = external_public_features(
        presence=presence,
        frequency=frequency,
        reference_rows=train_rows,
        target_rows=valid_rows,
        labels=labels,
        aa_clone_numbers=aa_clone_numbers,
        args=args,
        context="outer_validation_application",
        inner_fold=None,
        reference_rows_log=reference_rows_log,
    )

    train_with_public = assemble_model_dataframe(
        base, outer_train_ids, train_public, row_lookup
    )
    valid_with_public = assemble_model_dataframe(
        base, outer_valid_ids, valid_public, row_lookup
    )

    prediction_rows: List[Dict[str, object]] = []
    metric_rows: List[Dict[str, object]] = []
    coefficient_rows: List[Dict[str, object]] = []
    preprocess_rows: List[Dict[str, object]] = []

    for model_idx, (model_name, spec) in enumerate(model_specs.items()):
        X_train, X_valid, names, prep = build_design(
            train_with_public,
            valid_with_public,
            numeric_cols=spec["numeric"],
            categorical_cols=spec["categorical"],
            zero_sd_tolerance=args.zero_sd_tolerance,
        )
        for row in prep:
            row.update({
                "stage": "outer_final",
                "model": model_name,
                "inner_fold": "",
            })
        preprocess_rows.extend(prep)

        y_train = (
            train_with_public[args.label_col].str.upper()
            == args.positive_label.upper()
        ).astype(int).to_numpy()
        y_valid = (
            valid_with_public[args.label_col].str.upper()
            == args.positive_label.upper()
        ).astype(int).to_numpy()

        params = selected[model_name]
        model, converged, n_iter = fit_elastic_net(
            X_train,
            y_train,
            l1_ratio=params["l1_ratio"],
            lambda_value=params["lambda"],
            args=args,
            seed=derive_seed(args.seed, 400, model_idx),
        )
        probability = model.predict_proba(X_valid)[:, 1]
        threshold = params["threshold"]
        metrics = classification_metrics(y_valid, probability, threshold)
        metrics.update({
            "model": model_name,
            "model_definition": MODEL_LABELS[model_name],
            "outer_repeat": args.outer_repeat,
            "outer_fold": args.outer_fold,
            "n_outer_train": len(outer_train_ids),
            "n_outer_validation": len(outer_valid_ids),
            "selected_l1_ratio_alpha": params["l1_ratio"],
            "selected_lambda": params["lambda"],
            "inner_selected_roc_auc": params["inner_roc_auc"],
            "inner_selected_pr_auc": params["inner_pr_auc"],
            "fit_converged": converged,
            "iterations_used": n_iter,
            "n_final_predictors": len(names),
            "n_nonzero_coefficients": int(
                np.sum(np.abs(model.coef_.ravel()) > 1e-12)
            ),
        })
        metric_rows.append(metrics)

        predicted = (probability >= threshold).astype(int)
        for sample_id, y, prob, pred in zip(
            outer_valid_ids, y_valid, probability, predicted
        ):
            prediction_rows.append({
                "model": model_name,
                "outer_repeat": args.outer_repeat,
                "outer_fold": args.outer_fold,
                "sample_id": sample_id,
                "true_label": int(y),
                "true_cohort": (
                    args.positive_label if y == 1 else "RA"
                ),
                "probability_ILD": float(prob),
                "threshold": float(threshold),
                "predicted_label": int(pred),
                "predicted_cohort": (
                    args.positive_label if pred == 1 else "RA"
                ),
            })

        coefficient_rows.append({
            "model": model_name,
            "feature_name": "__INTERCEPT__",
            "coefficient": float(model.intercept_[0]),
            "absolute_coefficient": abs(float(model.intercept_[0])),
            "nonzero": True,
        })
        for name, coef in zip(names, model.coef_.ravel()):
            coefficient_rows.append({
                "model": model_name,
                "feature_name": name,
                "coefficient": float(coef),
                "absolute_coefficient": abs(float(coef)),
                "nonzero": bool(abs(coef) > 1e-12),
            })

    train_public_out = train_public.copy()
    train_public_out.insert(
        0,
        args.sample_id_col,
        [base.iloc[row][args.sample_id_col] for row in train_public_out.index],
    )
    valid_public_out = valid_public.copy()
    valid_public_out.insert(
        0,
        args.sample_id_col,
        [base.iloc[row][args.sample_id_col] for row in valid_public_out.index],
    )

    return (
        pd.DataFrame(prediction_rows),
        pd.DataFrame(metric_rows),
        pd.DataFrame(coefficient_rows),
        pd.DataFrame(preprocess_rows),
        train_public_out.reset_index(drop=True),
        valid_public_out.reset_index(drop=True),
    )


def output_paths(output_dir: Path) -> Dict[str, Path]:
    return {
        "configuration": output_dir / "05_trial_configuration.json",
        "sample_roles": output_dir / "05_trial_sample_roles.csv",
        "outer_train_public": (
            output_dir / "05_dynamic_public_features_outer_train_crossfit.csv"
        ),
        "outer_valid_public": (
            output_dir / "05_dynamic_public_features_outer_validation.csv"
        ),
        "public_reference_summary": (
            output_dir / "05_public_reference_build_summary.csv"
        ),
        "public_crossfit_assignments": (
            output_dir / "05_public_crossfit_assignments.csv"
        ),
        "inner_tuning": output_dir / "05_inner_tuning_results.csv",
        "inner_oof": output_dir / "05_inner_selected_oof_predictions.csv",
        "outer_predictions": (
            output_dir / "05_outer_validation_predictions.csv"
        ),
        "outer_metrics": output_dir / "05_outer_validation_metrics.csv",
        "coefficients": output_dir / "05_final_model_coefficients.csv",
        "preprocessing": output_dir / "05_preprocessing_summary.csv",
        "static_feature_list": output_dir / "05_static_tcr_feature_list.csv",
        "summary": output_dir / "05_single_outer_trial_summary.md",
    }


def enforce_overwrite(paths: Iterable[Path], overwrite: bool) -> None:
    existing = [p for p in paths if p.exists()]
    if existing and not overwrite:
        text = "\n".join(f"  - {p}" for p in existing)
        raise FileExistsError(
            "Outputs already exist. Add --overwrite:\n" + text
        )


def write_summary(
    path: Path,
    args: argparse.Namespace,
    n_train: int,
    n_valid: int,
    n_static: int,
    public_features: Sequence[str],
    metrics: pd.DataFrame,
    full_reference_counts: Optional[Mapping[str, int]],
    runtime: float,
) -> None:
    lines = [
        "# 05 Single Outer-Fold Trial Summary",
        "",
        "## Task",
        "",
        f"- Outer repeat: **{args.outer_repeat}**",
        f"- Outer fold: **{args.outer_fold}**",
        f"- Outer training samples: **{n_train}**",
        f"- Outer validation samples: **{n_valid}**",
        f"- Inner CV: **{args.inner_folds} folds**",
        f"- Public cross-fitting: **{args.public_crossfit_folds} folds**",
        "",
        "## Leakage controls",
        "",
        "- Independent test data were not read.",
        "- Outer validation samples were absent from all inner folds.",
        "- Every validation public feature used references from its corresponding training partition only.",
        "- Public features for model-fitting samples were cross-fitted without self-inclusion.",
        "- Encoding, zero-variance filtering and standardization were learned from each training partition only.",
        "",
        "## Feature definitions",
        "",
        f"- Static TCR features selected from manifest: **{n_static}**",
        f"- Public feature set: `{args.public_feature_set}`",
    ]
    lines.extend(f"- Public predictor: `{x}`" for x in public_features)

    if full_reference_counts is not None:
        lines.extend([
            "",
            "## Step-03 definition reproduction",
            "",
        ])
        for key, value in full_reference_counts.items():
            lines.append(f"- {key}: **{value:,}**")

    lines.extend([
        "",
        "## Outer validation results",
        "",
        "| Model | ROC-AUC | PR-AUC | Sensitivity | Specificity | F1 | Nonzero coefficients |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ])
    for _, row in metrics.iterrows():
        lines.append(
            f"| {row['model']} | {row['roc_auc']:.4f} | "
            f"{row['pr_auc']:.4f} | {row['sensitivity_recall']:.4f} | "
            f"{row['specificity']:.4f} | {row['f1']:.4f} | "
            f"{int(row['n_nonzero_coefficients'])} |"
        )

    lines.extend([
        "",
        "## Interpretation warning",
        "",
        "- This is one outer fold used to validate the implementation, not the final performance estimate.",
        "- Do not choose the final model from this single fold.",
        "- After checking outputs, the same workflow should be extended to all 100 outer tasks.",
        "",
        f"- Runtime: **{runtime:.2f} seconds**",
        "",
    ])
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    args = parse_args()
    started = time.time()

    (
        base,
        manifest,
        outer_task,
        inner_task,
        outer_train_ids,
        outer_valid_ids,
        input_paths,
    ) = read_core_inputs(args)

    output_dir = (
        Path(args.output_root).expanduser().resolve()
        / f"repeat_{args.outer_repeat:02d}_fold_{args.outer_fold:02d}"
    )
    output_dir.mkdir(parents=True, exist_ok=True)
    paths = output_paths(output_dir)
    enforce_overwrite(paths.values(), args.overwrite)

    static_features = static_tcr_features_from_manifest(manifest, base)
    public_features = PUBLIC_FEATURE_SETS[args.public_feature_set]
    model_specs = model_specifications(static_features, public_features, args)

    print("=" * 80)
    print("05 Single Outer-Fold Modeling Trial")
    print("=" * 80)
    print(
        f"Task: repeat={args.outer_repeat}, outer_fold={args.outer_fold}"
    )
    print(
        f"Outer train={len(outer_train_ids)}, "
        f"outer validation={len(outer_valid_ids)}"
    )
    print(f"Static TCR predictors: {len(static_features)}")
    print(
        f"Public predictor set: {args.public_feature_set} "
        f"({len(public_features)} features)"
    )
    print("Independent test set: NOT READ")
    print("")

    presence, frequency, cache_meta = build_or_load_sparse_cache(args, base)
    sample_ids = base.index.astype(str).tolist()
    row_lookup = {sample_id: i for i, sample_id in enumerate(sample_ids)}
    labels = base[args.label_col].astype(str).str.upper().to_numpy()
    aa_clone_numbers = pd.to_numeric(
        base[args.aa_clone_number_col], errors="raise"
    ).to_numpy(float)

    full_reference_counts = None
    if not args.skip_full_reference_validation:
        full_reference_counts = validate_full_reference(
            presence, labels, args
        )
        print(
            "[PASS] Full-train public reference sizes reproduce step-03: "
            + ", ".join(
                f"{k}={v:,}" for k, v in full_reference_counts.items()
            )
        )

    reference_rows_log: List[Dict[str, object]] = []
    crossfit_assignment_log: List[Dict[str, object]] = []

    prepared = prepare_inner_folds(
        base=base,
        inner_task=inner_task,
        outer_train_ids=outer_train_ids,
        row_lookup=row_lookup,
        presence=presence,
        frequency=frequency,
        labels=labels,
        aa_clone_numbers=aa_clone_numbers,
        model_specs=model_specs,
        args=args,
        reference_rows_log=reference_rows_log,
        crossfit_assignment_log=crossfit_assignment_log,
    )

    tuning, selected_oof, selected = tune_models(prepared, args)

    (
        outer_predictions,
        outer_metrics,
        coefficients,
        preprocessing,
        outer_train_public,
        outer_valid_public,
    ) = fit_outer_models(
        base=base,
        outer_train_ids=outer_train_ids,
        outer_valid_ids=outer_valid_ids,
        row_lookup=row_lookup,
        presence=presence,
        frequency=frequency,
        labels=labels,
        aa_clone_numbers=aa_clone_numbers,
        model_specs=model_specs,
        selected=selected,
        args=args,
        reference_rows_log=reference_rows_log,
        crossfit_assignment_log=crossfit_assignment_log,
    )

    roles = outer_task.copy()
    roles["selected_outer_task"] = np.where(
        roles["outer_fold"] == args.outer_fold,
        "validation",
        "training",
    )
    roles = roles[
        [
            "outer_repeat",
            "outer_fold",
            args.sample_id_col,
            args.label_col,
            "batch",
            "material",
            "sex",
            "selected_outer_task",
        ]
    ]

    static_feature_table = pd.DataFrame({
        "feature_order": np.arange(1, len(static_features) + 1),
        "feature_name": static_features,
    })

    reference_summary = pd.DataFrame(reference_rows_log)
    crossfit_assignments = pd.DataFrame(crossfit_assignment_log)
    if not crossfit_assignments.empty:
        crossfit_assignments[args.sample_id_col] = crossfit_assignments[
            "row_index"
        ].map({i: sid for i, sid in enumerate(sample_ids)})

    roles.to_csv(paths["sample_roles"], index=False)
    outer_train_public.to_csv(paths["outer_train_public"], index=False)
    outer_valid_public.to_csv(paths["outer_valid_public"], index=False)
    reference_summary.to_csv(paths["public_reference_summary"], index=False)
    crossfit_assignments.to_csv(
        paths["public_crossfit_assignments"], index=False
    )
    tuning.to_csv(paths["inner_tuning"], index=False)
    selected_oof.to_csv(paths["inner_oof"], index=False)
    outer_predictions.to_csv(paths["outer_predictions"], index=False)
    outer_metrics.to_csv(paths["outer_metrics"], index=False)
    coefficients.to_csv(paths["coefficients"], index=False)
    preprocessing.to_csv(paths["preprocessing"], index=False)
    static_feature_table.to_csv(paths["static_feature_list"], index=False)

    config = {
        "script_version": SCRIPT_VERSION,
        "outer_repeat": args.outer_repeat,
        "outer_fold": args.outer_fold,
        "input_files": {k: str(v) for k, v in input_paths.items()},
        "input_sha256": {
            k: sha256sum(v) for k, v in input_paths.items()
        },
        "public_catalog": str(Path(args.public_catalog).resolve()),
        "reference_definition": str(
            Path(args.reference_definition).resolve()
        ),
        "clone_table_dir": str(Path(args.clone_table_dir).resolve()),
        "cache_metadata": cache_meta,
        "n_outer_train": len(outer_train_ids),
        "n_outer_validation": len(outer_valid_ids),
        "n_static_tcr_features": len(static_features),
        "public_feature_set": args.public_feature_set,
        "public_predictors": public_features,
        "models": MODEL_LABELS,
        "l1_ratios_alpha": args.l1_ratios,
        "lambdas": args.lambdas,
        "class_weight": args.class_weight,
        "threshold_rule": "Youden J from selected inner OOF predictions",
        "public_thresholds": {
            "global_min_prevalence": args.global_min_prevalence,
            "global_min_count": args.global_min_count,
            "group_min_prevalence": args.group_min_prevalence,
            "group_min_count": args.group_min_count,
            "specific_prevalence_delta": args.specific_prevalence_delta,
            "epsilon": args.epsilon,
        },
        "selected_parameters": selected,
        "full_reference_counts": full_reference_counts,
        "seed": args.seed,
    }
    paths["configuration"].write_text(
        json.dumps(config, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    runtime = time.time() - started
    write_summary(
        path=paths["summary"],
        args=args,
        n_train=len(outer_train_ids),
        n_valid=len(outer_valid_ids),
        n_static=len(static_features),
        public_features=public_features,
        metrics=outer_metrics,
        full_reference_counts=full_reference_counts,
        runtime=runtime,
    )

    print("")
    print("[Selected parameters]")
    for model_name, params in selected.items():
        print(
            f"- {model_name}: alpha={params['l1_ratio']}, "
            f"lambda={params['lambda']}, "
            f"threshold={params['threshold']:.4f}, "
            f"inner AUC={params['inner_roc_auc']:.4f}"
        )
    print("")
    print("[Outer validation metrics]")
    print(
        outer_metrics[
            [
                "model",
                "roc_auc",
                "pr_auc",
                "sensitivity_recall",
                "specificity",
                "f1",
                "n_nonzero_coefficients",
                "fit_converged",
            ]
        ].to_string(index=False)
    )
    print("")
    print("[Output files]")
    for key, path in paths.items():
        print(f"- {key}: {path}")
    print(f"Runtime: {runtime:.2f}s")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise
