visualization:
  repository_root: .
  aggregation_dir: IGH/set/experiments/igh_linear_svm_all_feature14_repeat100_v1/03_summary
  output_dir: IGH/set/experiments/igh_linear_svm_all_feature14_repeat100_v1/06_visualization/main
  models: all
  performance_metrics:
  - roc_auc
  - average_precision
  - f1
  - sensitivity_recall
  - specificity
